services:
  mysql:
    container_name: mysqlhost
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=lakeview_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - lakeview-network

  app:
    container_name: lakeview-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file: "docker.env"
    networks:
      - lakeview-network

volumes:
  mysql_data:

networks:
  lakeview-network:
    driver: bridge